# frontend Dockerfile
FROM node:18

# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사
COPY frontend/package.json frontend/package-lock.json ./

# 의존성 설치
RUN npm install

# 소스 파일 복사
COPY frontend ./

# 빌드
RUN npm run build

# 포트 노출
EXPOSE 3000

# 애플리케이션 실행
CMD ["npm", "start"]
